import { useEffect, useState } from 'react'
import { useAuth } from '../context/AuthContext'
import { getProfile, updateProfile } from '../api/cases'

const blank = { fullName: '', role: '', department: '', organization: '' }
export default function ProfilePage() {
  const { user } = useAuth(); const [form, setForm] = useState(blank); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  useEffect(() => { getProfile().then(payload => setForm({ ...blank, ...(payload.profile || {}) })).catch(err => setError(err.message)).finally(() => setLoading(false)) }, [])
  const submit = async event => { event.preventDefault(); setSaving(true); setError(''); setMessage(''); try { const payload = await updateProfile(form); setForm({ ...blank, ...(payload.profile || {}) }); setMessage('Profile saved.') } catch (err) { setError(err.message) } finally { setSaving(false) } }
  return <section className="content px-4 py-7 md:px-10 md:py-10"><p className="eyebrow">Sentinel workspace</p><h1>Profile</h1><p className="muted">Manage safe account information. Authorization role is controlled by the system.</p>{error && <p className="form-error rounded-md p-3">{error}</p>}{message && <p className="form-success rounded-md p-3">{message}</p>}{loading ? <p className="muted">Loading profile...</p> : <form className="report-form" onSubmit={submit}><div className="form-grid grid gap-4 md:grid-cols-2"><label>Email Address<input value={user?.email || ''} readOnly /></label><label>Full Name<input value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} /></label><label>Role<input value={form.role} readOnly aria-readonly="true" /></label><label>Department<input value={form.department} onChange={e => setForm({ ...form, department: e.target.value })} /></label><label className="wide-field md:col-span-2">Organization<input value={form.organization} onChange={e => setForm({ ...form, organization: e.target.value })} /></label></div><div className="form-actions"><button className="button" disabled={saving}>{saving ? 'Saving...' : 'Save Profile'}</button></div></form>}</section>
}
